name: Deploy Project
on: [push, workflow_dispatch] #allow to be triggered on push or manually, can be unlimited options
defaults:
  run:
    working-directory: second-action-react-js #this sets the working directory for all steps
                                              #i have to do this cuz of proj set up
jobs:
  Run-Code-Tests: #can be named anything, it's the jobs title
    runs-on: ubuntu-latest #read docs to see pre-installed dependencies such as node.js
    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v3 #this is an offical action from github to get code from current repo
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: #configurations for used action
          node-version: 18
      - name: Install Dependencies
        run: npm ci #"ci" vs "install", ci uses the versions of packages that are in the package-lock while install does most recent version of package
      - name: Run Tests
        run: npm test
  Deploy-Code:
    needs: Run-Code-Tests #indicates that my first job needs to complete before running this job
                          #multiple jobs can be done with brackets [Run-Code-Tests, Second-Test, etc..]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v3 #this is an offical action from github to get code from current repo
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: #configurations for used action
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build #uses vite build to build proj
      - name: Deploy
        run: echo "Mock Deploy process..."

